name: Auto Push

on:
  push:
    branches:
      - main

jobs:
  push-to-remote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Push to remote repository
      env:
        PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote set-url origin https://${PAT}@github.com/${GITHUB_REPOSITORY}.git
        git push origin HEAD:main
