name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
    
    - name: Compile Java
      run: javac MemoryInfo.java
    
    - name: Check Python syntax
      run: python -m py_compile main.py
    
    - name: Test Flask app
      run: |
        python -c "from main import app; assert app is not None, 'Flask app not initialized'"

    # Add more tests here as needed

    - name: Print success message
      run: echo "CI passed successfully!"
